### ISSUE TITLE
Dependancies (LCLExtension, EpikTimer and VirtualTreeView) - issues installing

### ISSUE THREAD

**Issue by JernejL** [PascalRiekenberg/LazProfiler#1]
Could you please give some direct pointers at which versions of LCLExtension, EpikTimer and VirtualTreeView do we need and from which repositories? 
 
The wiki page has no info, i've spent days getting correct files and packages and i have lazarus 1.8.0 RC5, which is one of latest ones, and i can't get it working. 
 
Thank you.

**Comment by ghost** [comment]
First, you need Lazarus trunk version (http://wiki.lazarus.freepascal.org/Getting_Lazarus) as is described in forum topic, it's not working with standard Lazarus 1.8.0 RC5 I guess.

**Comment by PascalRiekenberg** [comment]
Yes, trunk is needed! Just use OnlinePackageManger to download and install. It will also install all depending packages.
