### ISSUE TITLE
Package compilation problem related to generics

### ISSUE THREAD

**Issue by zeljkoavramovic** [PascalRiekenberg/LazProfiler#3]
Both OPM and trunk versions have compilation problem on 32bit Lazarus 2.0 fixes FPC 3.0 fixes on Win10x64. This is the error:

> LazProfilerAddon.pas(24,3) Fatal: Cannot find Generics.Collections used by LazProfilerAddon of package LazProfiler.

**Comment by PascalRiekenberg** [comment]
Please see requirements in [wiki](http://wiki.freepascal.org/LazProfiler#System_Requirements_.2F_Dependencies) and OPM. You need at least fpc in version fixes_3_2 (or trunk).

**Comment by zeljkoavramovic** [comment]
Thank you. I didn't know that. Since many people will probably try to use via OPM in official Lazarus which still has FPC 3.0.x, it would be nice if compilation on FPC < 3.2 would produce the error.

Thank you for all the work!
